Cleanups and docs added to SUP and EIG. Update makefiles
Added doxygen doc to new SUP and EIG class. And a bit of cleanup.
Updated the makefiles for the new classes.

diff --git a/Makefile.intel-64 b/Makefile.intel-64
--- a/Makefile.intel-64
+++ b/Makefile.intel-64
@@ -15,12 +15,8 @@ CPPSRC	= sdp.cpp\
             PHM.cpp\
             DPM.cpp\
 	    PPHM.cpp\
-            SUP/SUP_PQ.cpp\
-            SUP/SUP_PQG.cpp\
-            SUP/SUP_PQGT1.cpp\
-            EIG/EIG_PQ.cpp\
-            EIG/EIG_PQG.cpp\
-            EIG/EIG_PQGT1.cpp
+	    SUP.cpp\
+	    EIG.cpp
 
 OBJ	= $(CPPSRC:.cpp=.o)
 
@@ -97,6 +93,18 @@ PQGT1:
 	   echo; echo '*************** FAILED! ***************' ; echo; \
 	 else \
 	   echo; echo '  +++ $(BINNAME) has been built with P, Q, G and T_1 conditions successfully!'; \
+	   echo; \
+	 fi
+
+PQGT2:
+	@echo
+	@echo '  +++ Building $(BINNAME) with P, Q, G and T_2 conditions'
+	@echo	
+	$(MAKE) $(BRIGHT_ROOT)/$(BINNAME) DEFS="-DPQGT2"
+	@if test $?; then \
+	   echo; echo '*************** FAILED! ***************' ; echo; \
+	 else \
+	   echo; echo '  +++ $(BINNAME) has been built with P, Q, G and T_2 conditions successfully!'; \
 	   echo; \
 	 fi
 
