Added the T2' Condition
Added a class for the T2' condition. The compiler flag is PQGT2P.

diff --git a/Makefile.gcc b/Makefile.gcc
--- a/Makefile.gcc
+++ b/Makefile.gcc
@@ -15,6 +15,7 @@ CPPSRC	= sdp.cpp\
             PHM.cpp\
             DPM.cpp\
 	    PPHM.cpp\
+	    T2PM.cpp\
 	    SUP.cpp\
 	    EIG.cpp
 
@@ -26,7 +27,7 @@ OBJ	= $(CPPSRC:.cpp=.o)
 
 BRIGHT_ROOT= .
 
-INCLUDE = -I
+INCLUDE =
 
 LIBS= -llapack -lblas
 
@@ -104,6 +105,18 @@ PQGT2:
 	   echo; echo '*************** FAILED! ***************' ; echo; \
 	 else \
 	   echo; echo '  +++ $(BINNAME) has been built with P, Q, G and T_2 conditions successfully!'; \
+	   echo; \
+	 fi
+
+PQGT2P:
+	@echo
+	@echo "  +++ Building $(BINNAME) with P, Q, G and T_2' conditions"
+	@echo	
+	$(MAKE) $(BRIGHT_ROOT)/$(BINNAME) DEFS="-DPQGT2P"
+	@if test $?; then \
+	   echo; echo '*************** FAILED! ***************' ; echo; \
+	 else \
+	   echo; echo "  +++ $(BINNAME) has been built with P, Q, G and T_2' conditions successfully!"; \
 	   echo; \
 	 fi
 
diff --git a/Makefile.intel-64 b/Makefile.intel-64
--- a/Makefile.intel-64
+++ b/Makefile.intel-64
@@ -15,6 +15,7 @@ CPPSRC	= sdp.cpp\
             PHM.cpp\
             DPM.cpp\
 	    PPHM.cpp\
+	    T2PM.cpp\
 	    SUP.cpp\
 	    EIG.cpp
 
@@ -105,6 +106,18 @@ PQGT2:
 	   echo; echo '*************** FAILED! ***************' ; echo; \
 	 else \
 	   echo; echo '  +++ $(BINNAME) has been built with P, Q, G and T_2 conditions successfully!'; \
+	   echo; \
+	 fi
+
+PQGT2P:
+	@echo
+	@echo "  +++ Building $(BINNAME) with P, Q, G and T_2' conditions"
+	@echo	
+	$(MAKE) $(BRIGHT_ROOT)/$(BINNAME) DEFS="-DPQGT2P"
+	@if test $?; then \
+	   echo; echo '*************** FAILED! ***************' ; echo; \
+	 else \
+	   echo; echo "  +++ $(BINNAME) has been built with P, Q, G and T_2' conditions successfully!"; \
 	   echo; \
 	 fi
 
